"""create initial tables

Revision ID: 3e5f3361d194
Revises: 
Create Date: 2026-05-18 11:10:01.071371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e5f3361d194'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('current_vehicle_state',
    sa.Column('plate_number', sa.String(), nullable=False),
    sa.Column('current_floor', sa.Integer(), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('plate_number')
    )
    op.create_index(op.f('ix_current_vehicle_state_plate_number'), 'current_vehicle_state', ['plate_number'], unique=False)
    op.create_table('vehicle_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plate_number', sa.String(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('checkpoint', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_events_plate_number'), 'vehicle_events', ['plate_number'], unique=False)
    op.create_index(op.f('ix_vehicle_events_timestamp'), 'vehicle_events', ['timestamp'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plate_number', sa.String(), nullable=False),
    sa.Column('owner_phone', sa.String(), nullable=True),
    sa.Column('vehicle_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_plate_number'), 'vehicles', ['plate_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_plate_number'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_vehicle_events_timestamp'), table_name='vehicle_events')
    op.drop_index(op.f('ix_vehicle_events_plate_number'), table_name='vehicle_events')
    op.drop_table('vehicle_events')
    op.drop_index(op.f('ix_current_vehicle_state_plate_number'), table_name='current_vehicle_state')
    op.drop_table('current_vehicle_state')
    # ### end Alembic commands ###
